--CREATE DATABASE db_medtech

CREATE TABLE PATIENT (
	idPatient INT IDENTITY(1, 1) PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL,
	birthDate DATE NOT NULL,
	phoneNumber VARCHAR(11),
	healthInsurance VARCHAR(50),
	password VARCHAR(255) NOT NULL,
	createdAt DATETIME DEFAULT(GETDATE()),
	updatedAt DATETIME
)
GO
CREATE TRIGGER TRG_PATIENT_updatedAt ON PATIENT FOR UPDATE AS
BEGIN
  UPDATE PATIENT
	SET updatedAt = GETDATE()
	FROM PATIENT INNER JOIN deleted d
	ON PATIENT.idPatient=d.idPatient
END
GO

CREATE TABLE DOCTOR (
	idDoctor INT IDENTITY(1, 1) PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL,
	birthDate DATE NOT NULL,
	phoneNumber VARCHAR(11),
	specialty VARCHAR(50) NOT NULL,
	city VARCHAR(50) NOT NULL,
	address VARCHAR(200) NOT NULL,
	password VARCHAR(255) NOT NULL,
	createdAt DATETIME DEFAULT(GETDATE()),
	updatedAt DATETIME
)
GO
CREATE TRIGGER TRG_DOCTOR_updatedAt ON DOCTOR FOR UPDATE AS
BEGIN
  UPDATE DOCTOR
	SET updatedAt = GETDATE()
	FROM DOCTOR INNER JOIN deleted d
	ON DOCTOR.idDoctor=d.idDoctor
END
GO

CREATE TABLE SCHEDULE (
	idSchedule INT IDENTITY(1, 1) PRIMARY KEY,
	idDoctor INT FOREIGN KEY REFERENCES DOCTOR(idDoctor) NOT NULL,
	weekDay VARCHAR(20) NOT NULL CHECK (weekDay IN ('Segunda-feira', 'Terça-feira', 'Quarta-feira', 'Quinta-feira', 'Sexta-feira', 'Sábado', 'Domingo')),
	startTime TIME NOT NULL,
	endTime TIME NOT NULL,
	createdAt DATETIME DEFAULT(GETDATE()),
	updatedAt DATETIME
)
GO
CREATE TRIGGER TRG_SCHEDULE_updatedAt ON SCHEDULE FOR UPDATE AS
BEGIN
  UPDATE SCHEDULE
	SET updatedAt = GETDATE()
	FROM SCHEDULE INNER JOIN deleted d
	ON SCHEDULE.idSchedule=d.idSchedule
END
GO

CREATE TABLE APPOINTMENT (
	idAppointment INT IDENTITY(1, 1) PRIMARY KEY,
	idSchedule INT FOREIGN KEY REFERENCES SCHEDULE(idSchedule) NOT NULL,
	idPatient INT FOREIGN KEY REFERENCES PATIENT(idPatient) NOT NULL,
	appointmentDate DATE NOT NULL,
	createdAt DATETIME DEFAULT(GETDATE()),
	updatedAt DATETIME
)
GO
CREATE TRIGGER TRG_APPOINTMENT_updatedAt ON APPOINTMENT FOR UPDATE AS
BEGIN
  UPDATE APPOINTMENT
	SET updatedAt = GETDATE()
	FROM APPOINTMENT INNER JOIN deleted d
	ON APPOINTMENT.idAppointment=d.idAppointment
END
GO